// This file is auto-generated by scripts/generateStaticImageMap.js. Do not edit directly.

export const archiveImages: Record<string, { thumbnail: string | null; gallery: string[] }> = {
  "bola-takraw": {
    "thumbnail": "/archive/bola-takraw/thumbnail.jpg",
    "gallery": [
      "/archive/bola-takraw/detail-1.jpg"
    ]
  },
  "dingklik": {
    "thumbnail": "/archive/dingklik/thumbnail.jpg",
    "gallery": [
      "/archive/dingklik/detail-1.jpg",
      "/archive/dingklik/detail-2.jpg",
      "/archive/dingklik/detail-3.jpg"
    ]
  },
  "gantungan-kunci": {
    "thumbnail": "/archive/gantungan-kunci/thumbnail.jpg",
    "gallery": []
  },
  "gelas": {
    "thumbnail": "/archive/gelas/thumbnail.jpg",
    "gallery": [
      "/archive/gelas/detail-1.jpg",
      "/archive/gelas/detail-2.jpg"
    ]
  },
  "hiasan-dinding": {
    "thumbnail": "/archive/hiasan-dinding/thumbnail.jpg",
    "gallery": [
      "/archive/hiasan-dinding/detail-1.jpg",
      "/archive/hiasan-dinding/detail-2.HEIC",
      "/archive/hiasan-dinding/detail-3.HEIC"
    ]
  },
  "hulahoop": {
    "thumbnail": "/archive/hulahoop/thumbnail.jpg",
    "gallery": []
  },
  "kursi-bonceng": {
    "thumbnail": "/archive/kursi-bonceng/thumbnail.png",
    "gallery": [
      "/archive/kursi-bonceng/detail-1.png",
      "/archive/kursi-bonceng/detail-2.png",
      "/archive/kursi-bonceng/detail-3.png"
    ]
  },
  "kursi-lengkung": {
    "thumbnail": null,
    "gallery": []
  },
  "kursi-momon": {
    "thumbnail": null,
    "gallery": []
  },
  "kursi-sofa-ece": {
    "thumbnail": "/archive/kursi-sofa-ece/thumbnail.jpg",
    "gallery": [
      "/archive/kursi-sofa-ece/detail-1.jpg",
      "/archive/kursi-sofa-ece/detail-2.jpg",
      "/archive/kursi-sofa-ece/detail-3.jpg",
      "/archive/kursi-sofa-ece/detail-4.jpg"
    ]
  },
  "lonceng": {
    "thumbnail": "/archive/lonceng/thumbnail.png",
    "gallery": [
      "/archive/lonceng/detail-1.png",
      "/archive/lonceng/detail-2.png",
      "/archive/lonceng/detail-3.png",
      "/archive/lonceng/detail-4.png",
      "/archive/lonceng/detail-5.png",
      "/archive/lonceng/detail-6.png"
    ]
  },
  "sesaji": {
    "thumbnail": "/archive/sesaji/thumbnail.jpg",
    "gallery": []
  },
  "teko": {
    "thumbnail": "/archive/teko/thumbnail.jpg",
    "gallery": [
      "/archive/teko/detail-1.jpg"
    ]
  },
  "tempat-teh": {
    "thumbnail": "/archive/tempat-teh/thumbnail.jpg",
    "gallery": [
      "/archive/tempat-teh/detail-1.jpg",
      "/archive/tempat-teh/detail-2.jpg"
    ]
  }
};

export const craftsmenImages: Record<string, { thumbnail: string | null; gallery: string[] }> = {
  "mas-teguh": {
    "thumbnail": "/craftsmen/mas-teguh/thumbnail.jpg",
    "gallery": []
  },
  "pak-andi": {
    "thumbnail": "/craftsmen/pak-andi/thumbnail.jpg",
    "gallery": [
      "/craftsmen/pak-andi/detail-1.JPG",
      "/craftsmen/pak-andi/detail-2.jpg",
      "/craftsmen/pak-andi/detail-3.jpg"
    ]
  },
  "pak-ari": {
    "thumbnail": "/craftsmen/pak-ari/thumbnail.jpg",
    "gallery": []
  },
  "pak-bambang": {
    "thumbnail": "/craftsmen/pak-bambang/thumbnail.jpg",
    "gallery": []
  },
  "pak-daliman": {
    "thumbnail": "/craftsmen/pak-daliman/thumbnail.jpg",
    "gallery": [
      "/craftsmen/pak-daliman/detail-1.jpg"
    ]
  },
  "pak-heru": {
    "thumbnail": "/craftsmen/pak-heru/thumbnail.jpg",
    "gallery": []
  },
  "pak-ikhsan": {
    "thumbnail": "/craftsmen/pak-ikhsan/thumbnail.jpg",
    "gallery": []
  },
  "pak-marjono": {
    "thumbnail": "/craftsmen/pak-marjono/thumbnail.jpg",
    "gallery": [
      "/craftsmen/pak-marjono/detail-1.jpg"
    ]
  },
  "pak-muklis": {
    "thumbnail": "/craftsmen/pak-muklis/thumbnail.HEIC",
    "gallery": []
  },
  "pak-pungky": {
    "thumbnail": "/craftsmen/pak-pungky/thumbnail.JPG",
    "gallery": [
      "/craftsmen/pak-pungky/detail-1.JPG",
      "/craftsmen/pak-pungky/detail-2.JPG",
      "/craftsmen/pak-pungky/detail-3.JPG",
      "/craftsmen/pak-pungky/detail-4.JPG",
      "/craftsmen/pak-pungky/detail-5.JPG"
    ]
  },
  "pak-purnomo": {
    "thumbnail": "/craftsmen/pak-purnomo/thumbnail.jpeg",
    "gallery": []
  },
  "pak-sarbini": {
    "thumbnail": "/craftsmen/pak-sarbini/thumbnail.jpg",
    "gallery": []
  },
  "pak-sardimin": {
    "thumbnail": "/craftsmen/pak-sardimin/thumbnail.JPG",
    "gallery": [
      "/craftsmen/pak-sardimin/detail-1.jpg",
      "/craftsmen/pak-sardimin/detail-2.HEIC"
    ]
  },
  "pak-sardjito": {
    "thumbnail": "/craftsmen/pak-sardjito/thumbnail.jpg",
    "gallery": []
  },
  "pak-seno": {
    "thumbnail": "/craftsmen/pak-seno/thumbnail.jpg",
    "gallery": []
  },
  "pak-sukino": {
    "thumbnail": "/craftsmen/pak-sukino/thumbnail.jpg",
    "gallery": []
  },
  "pak-suparmin": {
    "thumbnail": "/craftsmen/pak-suparmin/thumbnail.jpg",
    "gallery": []
  },
  "pak-supri": {
    "thumbnail": "/craftsmen/pak-supri/thumbnail.jpg",
    "gallery": []
  },
  "pak-suwarto": {
    "thumbnail": "/craftsmen/pak-suwarto/thumbnail.jpg",
    "gallery": [
      "/craftsmen/pak-suwarto/detail-1.jpg",
      "/craftsmen/pak-suwarto/detail-2.jpg",
      "/craftsmen/pak-suwarto/detail-3.jpg"
    ]
  },
  "pak-triyono": {
    "thumbnail": "/craftsmen/pak-triyono/thumbnail.jpg",
    "gallery": [
      "/craftsmen/pak-triyono/detail-1.jpg"
    ]
  },
  "pak-warsino": {
    "thumbnail": "/craftsmen/pak-warsino/thumbnail.JPG",
    "gallery": [
      "/craftsmen/pak-warsino/detail-1.JPG",
      "/craftsmen/pak-warsino/detail-2.HEIC",
      "/craftsmen/pak-warsino/detail-3.HEIC",
      "/craftsmen/pak-warsino/detail-4.HEIC",
      "/craftsmen/pak-warsino/detail-5.jpg"
    ]
  },
  "putra-istana-rotan": {
    "thumbnail": "/craftsmen/putra-istana-rotan/thumbnail-pak-wisnu.jpg",
    "gallery": [
      "/craftsmen/putra-istana-rotan/detail-1-bu-broto.jpg",
      "/craftsmen/putra-istana-rotan/detail-2-mas-joni.jpg"
    ]
  },
  "tina-rotan": {
    "thumbnail": "/craftsmen/tina-rotan/thumbnail.JPG",
    "gallery": [
      "/craftsmen/tina-rotan/detail-1.JPG",
      "/craftsmen/tina-rotan/detail-2.jpg",
      "/craftsmen/tina-rotan/detail-3.jpg"
    ]
  }
};

export const eventImages: Record<string, { thumbnail: string | null; gallery: string[] }> = {
  "menjalin-penjalin": {
    "thumbnail": "/events/menjalin-penjalin/thumbnail.png",
    "gallery": [
      "/events/menjalin-penjalin/detail-1.jpg"
    ]
  }
};
